"init"
let mapleader = "\<Space>" 
let maplocalleader = ","
set runtimepath+=$HOME/.vim



"=VimPlug="
"https://github.com/junegunn/vim-plug"

"Install vimplug and dirs if not available"
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"Setting termguicolors"
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX) && getenv('TERM_PROGRAM') != 'Apple_Terminal')
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif


"check if plugged exists"
if !isdirectory(expand("~/.vim/plugged"))
    call mkdir($HOME . "/.vim/plugged")
endif


"Plugin install"
call plug#begin('~/.vim/plugged')

  "ui"
  Plug 'morhetz/gruvbox'
  Plug 'vim-airline/vim-airline' 
  Plug 'vim-airline/vim-airline-themes'

  "util"
  Plug 'tpope/vim-commentary'
  Plug 'mg979/vim-visual-multi', {'branch': 'master'}
  Plug 'tpope/vim-surround'
  Plug 'bkad/CamelCaseMotion'
  Plug 'machakann/vim-highlightedyank'
  Plug 'wellle/targets.vim'
  Plug 'vim-scripts/AutoComplPop'
  Plug 'matze/vim-move'
  Plug 'AndrewRadev/splitjoin.vim'
  Plug 'jiangmiao/auto-pairs'
  Plug 'suy/vim-context-commentstring'
  Plug 'voldikss/vim-floaterm'
  Plug 'unblevable/quick-scope'
  Plug 'justinmk/vim-sneak'


  


  "configure these"
  Plug 'scrooloose/nerdtree' | 
   \ Plug 'Xuyuanp/nerdtree-git-plugin' |
   \ Plug 'philrunninger/nerdtree-visual-selection'

  " if has('nvim') || has('patch-8.0.902')
  "   Plug 'mhinz/vim-signify'
  " else
  "   Plug 'mhinz/vim-signify', { 'tag': 'legacy' }
  " endif
  "
  " Plug 'tpope/vim-fugitive'

  "needs configing"
  Plug 'godlygeek/tabular'
  Plug 'kshenoy/vim-signature'

  " Plug 'ctrlpvim/ctrlp.vim'
  " Plug 'mhinz/vim-grepper'
  " Plug 'honza/vim-snippets'
  " Plug 'tommcdo/vim-exchange'
  "
  "lsp and completion"

  "which one?"
  " Plug 'dense-analysis/ale'
  " Plug 'prabirshrestha/vim-lsp'

  "Languages and files"


  "misc"




call plug#end()


" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif



"plugin config files"

func! SourceConfigs(filename)
  execute "silent source" . $HOME . "/.vim/config/" . a:filename
endfunc

"common"
call SourceConfigs("gruvbox.vim")
call SourceConfigs("camelcase.vim")
call SourceConfigs("highlight.vim")
call SourceConfigs("airline.vim")
call SourceConfigs("tabular.vim")
call SourceConfigs("nerd.vim")
call SourceConfigs("nerd-git.vim")
call SourceConfigs("nerd-visual.vim")
call SourceConfigs("ctrlp.vim")
call SourceConfigs("visual-multi.vim")
call SourceConfigs("sneak.vim")


"lsp and code"
" call SourceConfigs("/code/ale.vim")
" call SourceConfigs("/code/comp.vim")
" call SourceConfigs("/code/lsp.vim")
"

